baseURL = "https://schertel.dev/"
languageCode = "en-us"

title = "Matias Schertel.dev"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
defaultContentLanguage = "en"

theme = "hallo"

googleAnalytics = "UA-177415271-1"

[Author]
    name = "Matias Schertel ♾️🌈"

[params]
    description = "Personal landing page for Matias Schertel."

    [params.colors]
        background = "#000000"
        foreground = "#FFFFFF"
        hover = "#9B4F96"

    [[params.links]]
        icon = "mastodon"
        title = "Mastodon"
        url = "https://fosstodon.org/@flatline"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/flatlining"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/flatlining/"
    [[params.links]]
        icon = "docker"
        title = "Docker"
        url = "https://hub.docker.com/u/flatlining"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/flatlining"
    [[params.links]]
        icon = "steam"
        title = "Steam"
        url = "https://steamcommunity.com/id/sadrunk/"
    [[params.links]]
        iconset = "fas"
        icon = "at"
        title = "E-mail"
        url = "mailto:matias@schertel.dev"
    [[params.links]]
        iconset = "fas"
        icon = "blog"
        title = "Blog"
        url = "https://schertel.dev/blog/"
    [[params.links]]
        iconset = "fas"
        icon = "file"
        title = "Resume"
        url = "https://schertel.dev/"
    [[params.links]]
        iconset = "fas"
        icon = "key"
        title = "PGP Public Key Block for mschertel@gmail.com"
        url = "/key.asc"
